import { useEffect, useMemo, useState } from 'react';
import {
  Alert, Box, Button, Card, CardContent, Checkbox, Chip, Container, FormControl,
  Grid, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography
} from '@mui/material';

const API='/api';
const hoje=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};

function Chamada({ professor, token }) {
  const [dados,setDados]=useState({disciplinas:[],turmas:[]});
  const [turmaId,setTurmaId]=useState(''); const [disciplinaId,setDisciplinaId]=useState('');
  const [dataAula,setDataAula]=useState(hoje()); const [qtd,setQtd]=useState(1); const [plano,setPlano]=useState('');
  const [faltas,setFaltas]=useState({}); const [msg,setMsg]=useState('');
  const headers={Authorization:`Bearer ${token}`};
  const carregar=async()=>{const r=await fetch(`${API}/chamada/dados`,{headers}); const j=await r.json(); if(!r.ok) throw Error(j.erro||'Erro ao carregar chamada'); setDados(j); if(j.disciplinas?.length && !disciplinaId) setDisciplinaId(String(j.disciplinas[0].id));};
  useEffect(()=>{carregar().catch(e=>setMsg(e.message));},[]);
  const turmasFiltradas=useMemo(()=>dados.turmas.filter(t=>!disciplinaId || Number(t.disciplina_id)===Number(disciplinaId)),[dados.turmas,disciplinaId]);
  const turma=dados.turmas.find(t=>Number(t.id)===Number(turmaId));
  const marcarFalta=(alunoId,aula,valor)=>setFaltas(prev=>{const key=`${alunoId}-${aula}`; const next={...prev}; if(valor) next[key]=true; else delete next[key]; return next;});
  const salvar=async(e)=>{e.preventDefault();setMsg(''); if(!turmaId||!disciplinaId||!dataAula||!plano.trim()){setMsg('Preencha turma, data e título do plano de aula.');return;} const lista=[]; Object.keys(faltas).forEach(k=>{const [aluno_id,aula_numero]=k.split('-').map(Number);lista.push({aluno_id,aula_numero});}); try{const r=await fetch(`${API}/chamada`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({turma_id:Number(turmaId),disciplina_id:Number(disciplinaId),data_aula:dataAula,quantidade_aulas:Number(qtd),plano_aula:plano,faltas:lista})});const j=await r.json();if(!r.ok)throw Error(j.erro||'Erro ao salvar chamada');setMsg(`Chamada salva! ${j.registros} registros, ${j.faltas} falta(s).`);setFaltas({});}catch(e){setMsg(e.message)}};
  return <Stack spacing={3}>
    <Box><Typography variant="h5" fontWeight={700}>📋 Fazer Chamada</Typography><Typography color="text.secondary">Professor: <strong>{professor.nome}</strong></Typography></Box>
    {msg&&<Alert severity={msg.includes('salva')||msg.includes('sucesso')?'success':'warning'}>{msg}</Alert>}
    <Paper variant="outlined" sx={{p:3,borderRadius:3}}><form onSubmit={salvar}><Grid container spacing={2}>
      <Grid item xs={12} md={4}><FormControl fullWidth required><InputLabel>Disciplina</InputLabel><Select value={disciplinaId} label="Disciplina" onChange={e=>{setDisciplinaId(e.target.value);setTurmaId('')}}>{dados.disciplinas.map(d=><MenuItem key={d.id} value={d.id}>{d.nome}</MenuItem>)}</Select></FormControl></Grid>
      <Grid item xs={12} md={4}><FormControl fullWidth required><InputLabel>Turma</InputLabel><Select value={turmaId} label="Turma" onChange={e=>setTurmaId(e.target.value)}><MenuItem value="">Selecione</MenuItem>{turmasFiltradas.map(t=><MenuItem key={t.id} value={t.id}>{t.nome} — {t.serie}</MenuItem>)}</Select></FormControl></Grid>
      <Grid item xs={12} md={4}><TextField fullWidth required type="date" label="Data da aula" value={dataAula} onChange={e=>setDataAula(e.target.value)} InputLabelProps={{shrink:true}}/></Grid>
      <Grid item xs={12} md={3}><TextField fullWidth required type="number" label="Quantidade de aulas" value={qtd} onChange={e=>setQtd(Math.max(1,Math.min(20,Number(e.target.value)||1)))} inputProps={{min:1,max:20}}/></Grid>
      <Grid item xs={12} md={9}><TextField fullWidth required label="Título do plano de aula" value={plano} onChange={e=>setPlano(e.target.value)} placeholder="Ex.: Equações do 2º grau"/></Grid>
    </Grid>
    {turma&&<Box sx={{mt:3,overflowX:'auto'}}><Typography variant="h6" sx={{mb:1}}>Alunos — marque a falta em cada aula</Typography><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:10}}>Aluno</th>{Array.from({length:qtd},(_,i)=><th key={i} style={{padding:10}}>Aula {i+1}<br/><small>Falta</small></th>)}</tr></thead><tbody>{(turma.alunos||[]).map(a=><tr key={a.id}><td style={{padding:10,borderTop:'1px solid #ddd'}}>{a.nome}</td>{Array.from({length:qtd},(_,i)=>{const key=`${a.id}-${i+1}`;return <td key={i} style={{textAlign:'center',borderTop:'1px solid #ddd'}}><Checkbox checked={!!faltas[key]} onChange={e=>marcarFalta(a.id,i+1,e.target.checked)} /></td>})}</tr>)}</tbody></table>{(!turma.alunos||turma.alunos.length===0)&&<Alert severity="info" sx={{mt:2}}>Esta turma não possui alunos vinculados.</Alert>}</Box>}
    <Button type="submit" variant="contained" size="large" disabled={!turmaId}>Salvar Chamada</Button></form></Paper>
  </Stack>;
}

function App(){
  const [token,setToken]=useState(()=>sessionStorage.getItem('sistema_token')||'');
  const [professor,setProfessor]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('sistema_professor')||'null')}catch{return null}});
  const [login,setLogin]=useState({usuario:'',senha:''}); const [loginMsg,setLoginMsg]=useState('');
  const [view,setView]=useState('chamada'); const [alunos,setAlunos]=useState([]); const [turmas,setTurmas]=useState([]); const [msg,setMsg]=useState('');
  const [alunoForm,setAlunoForm]=useState({nome:'',email:'',data_nascimento:'',serie:'',cpf:'',telefone:'',endereco:''});
  const [turmaForm,setTurmaForm]=useState({nome:'',serie:'',ano:new Date().getFullYear().toString(),alunosIds:[]});
  const carregar=async()=>{try{const [a,t]=await Promise.all([fetch(`${API}/alunos`),fetch(`${API}/turmas`)]);if(a.ok)setAlunos(await a.json());if(t.ok)setTurmas(await t.json());}catch{}}
  useEffect(()=>{if(token)carregar()},[token]);
  const entrar=async e=>{e.preventDefault();setLoginMsg('');try{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});const j=await r.json();if(!r.ok)throw Error(j.erro||'Falha no login');sessionStorage.setItem('sistema_token',j.token);sessionStorage.setItem('sistema_professor',JSON.stringify(j.professor));setToken(j.token);setProfessor(j.professor);}catch(e){setLoginMsg(e.message)}};
  const sair=async()=>{if(token)await fetch(`${API}/auth/logout`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}).catch(()=>{});sessionStorage.clear();setToken('');setProfessor(null)};
  const cadastrarAluno=async e=>{e.preventDefault();setMsg('');const r=await fetch(`${API}/alunos`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(alunoForm)});const j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.erro||j.message||'Erro ao cadastrar aluno');return}setMsg('Aluno cadastrado com sucesso!');setAlunoForm({nome:'',email:'',data_nascimento:'',serie:'',cpf:'',telefone:'',endereco:''});carregar()};
  const cadastrarTurma=async e=>{e.preventDefault();const r=await fetch(`${API}/turmas`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(turmaForm)});const j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.erro||'Erro ao cadastrar turma');return}setMsg('Turma cadastrada com sucesso!');setTurmaForm({nome:'',serie:'',ano:new Date().getFullYear().toString(),alunosIds:[]});carregar()};
  if(!token||!professor)return <Container maxWidth="sm" sx={{py:8}}><Paper elevation={6} sx={{p:5,borderRadius:4}}><Stack spacing={3}><Box textAlign="center"><Typography variant="h4" fontWeight={700}>Sistema Escolar</Typography><Typography color="text.secondary">Login do professor</Typography></Box><form onSubmit={entrar}><Stack spacing={2}><TextField required fullWidth label="Usuário" value={login.usuario} onChange={e=>setLogin({...login,usuario:e.target.value})}/><TextField required fullWidth label="Senha" type="password" value={login.senha} onChange={e=>setLogin({...login,senha:e.target.value})}/>{loginMsg&&<Alert severity="error">{loginMsg}</Alert>}<Button type="submit" variant="contained" size="large">Entrar</Button></Stack></form><Alert severity="info">Acesso de demonstração: <strong>professor</strong> / <strong>1234</strong></Alert></Stack></Paper></Container>;
  return <Container maxWidth="xl" sx={{py:4}}><Paper elevation={3} sx={{p:{xs:2,md:4},borderRadius:4}}><Stack spacing={3}><Box sx={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:2,flexWrap:'wrap'}}><Box><Typography variant="h4" fontWeight={700}>Painel do Professor</Typography><Typography color="text.secondary">{professor.nome} • {professor.disciplinas?.map(d=>d.nome).join(', ')}</Typography></Box><Button variant="outlined" onClick={sair}>Sair</Button></Box>
    <Stack direction={{xs:'column',sm:'row'}} spacing={2}><Button variant={view==='chamada'?'contained':'outlined'} onClick={()=>setView('chamada')}>📋 Fazer Chamada</Button><Button variant={view==='alunos'?'contained':'outlined'} onClick={()=>setView('alunos')}>Alunos</Button><Button variant={view==='turmas'?'contained':'outlined'} onClick={()=>setView('turmas')}>Turmas</Button></Stack>
    {view==='chamada'&&<Chamada professor={professor} token={token}/>} 
    {view==='alunos'&&<Paper variant="outlined" sx={{p:3}}><Typography variant="h5" sx={{mb:2}}>Cadastro de Alunos</Typography>{msg&&<Alert sx={{mb:2}} severity={msg.includes('sucesso')?'success':'error'}>{msg}</Alert>}<form onSubmit={cadastrarAluno}><Grid container spacing={2}><Grid item xs={12} md={6}><TextField fullWidth required label="Nome" value={alunoForm.nome} onChange={e=>setAlunoForm({...alunoForm,nome:e.target.value})}/></Grid><Grid item xs={12} md={6}><TextField fullWidth required type="email" label="E-mail" value={alunoForm.email} onChange={e=>setAlunoForm({...alunoForm,email:e.target.value})}/></Grid><Grid item xs={12} md={6}><TextField fullWidth required type="date" label="Data de nascimento" value={alunoForm.data_nascimento} onChange={e=>setAlunoForm({...alunoForm,data_nascimento:e.target.value})} InputLabelProps={{shrink:true}}/></Grid><Grid item xs={12} md={6}><TextField select fullWidth required label="Série" value={alunoForm.serie} onChange={e=>setAlunoForm({...alunoForm,serie:e.target.value})}>{['1º Ano','2º Ano','3º Ano','4º Ano','5º Ano'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></Grid></Grid><Button sx={{mt:2}} type="submit" variant="contained">Cadastrar aluno</Button></form><Stack spacing={1} sx={{mt:3}}>{alunos.map(a=><Card key={a.id}><CardContent><Typography fontWeight={600}>{a.nome}</Typography><Typography variant="body2" color="text.secondary">{a.email} • {a.serie}</Typography></CardContent></Card>)}</Stack></Paper>}
    {view==='turmas'&&<Paper variant="outlined" sx={{p:3}}><Typography variant="h5">Cadastro de Turmas</Typography>{msg&&<Alert sx={{my:2}} severity={msg.includes('sucesso')?'success':'error'}>{msg}</Alert>}<form onSubmit={cadastrarTurma}><Grid container spacing={2} sx={{mt:1}}><Grid item xs={12} md={4}><TextField fullWidth required label="Nome da turma" value={turmaForm.nome} onChange={e=>setTurmaForm({...turmaForm,nome:e.target.value})}/></Grid><Grid item xs={12} md={4}><TextField select fullWidth required label="Série" value={turmaForm.serie} onChange={e=>setTurmaForm({...turmaForm,serie:e.target.value})}>{['1º Ano','2º Ano','3º Ano','4º Ano','5º Ano'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></Grid><Grid item xs={12} md={4}><TextField fullWidth required type="number" label="Ano letivo" value={turmaForm.ano} onChange={e=>setTurmaForm({...turmaForm,ano:e.target.value})}/></Grid></Grid><Button sx={{mt:2}} type="submit" variant="contained">Salvar turma</Button></form><Stack spacing={2} sx={{mt:3}}>{turmas.map(t=><Card key={t.id}><CardContent><Typography fontWeight={700}>{t.nome}</Typography><Typography variant="body2">{t.serie} • {t.ano} • {t.disciplina?.nome||'Sem disciplina'}</Typography><Typography variant="body2" color="text.secondary">Alunos: {(t.alunos||[]).map(a=>a.nome).join(', ')||'nenhum'}</Typography></CardContent></Card>)}</Stack></Paper>}
  </Stack></Paper></Container>;
}
export default App;
